export const HEALTH_CATEGORIES = [
  {
    id: "mental",
    title: "Mental Wellbeing",
    icon: "Brain",
    color: "text-purple-400",
    questions: [
      "Why do I feel tired but wired at night?",
      "Is my 'laziness' actually burnout?",
      "How to stop overthinking before bed instantly?",
      "Why can't I focus for more than 10 minutes?",
      "Signs of adult ADHD nobody talks about",
      "Why do I wake up feeling anxious?",
      "Am I dissociated or just zoning out?",
      "Why do I get angry at loud chewing?",
      "How to reset brain after doom-scrolling?",
      "Why do I feel guilty when relaxing?",
      "Feeling empty inside but don't know why",
      "Why do I sabotage good things in life?",
      "Racing thoughts keeping me awake",
      "Is it depression or just a bad phase?",
      "Why do I feel numb emotionally?",
      "Can't stop picking at my skin",
      "Why do I need constant validation?",
      "Feeling like I'm watching my life happen",
      "Why do I procrastinate everything?"
    ]
  },
  {
    id: "substances",
    title: "Substances & Effects",
    icon: "AlertCircle",
    color: "text-red-400",
    questions: [
      "How long does weed stay in system?",
      "Why do I feel anxious after drinking?",
      "Is microdosing actually safe?",
      "Cocaine comedown: How long does it last?",
      "Why does alcohol make me depressed?",
      "Signs of alcohol poisoning vs hangover",
      "Can you overdose on edibles?",
      "Why do stimulants make me calm?",
      "How to sober up fast for work?",
      "Is my tolerance getting dangerous?",
      "Weed making me paranoid lately",
      "Can I drink on antidepressants?",
      "Why do I blackout after few drinks?",
      "Nicotine withdrawal symptoms timeline",
      "Is vaping worse than smoking?",
      "Why does caffeine make me tired?",
      "Mixing alcohol and weed effects",
      "How to pass a drug test fast?",
      "Why do I crave alcohol when stressed?",
      "Is kratom actually safe?"
    ]
  },
  {
    id: "sexual",
    title: "Sexual Health",
    icon: "Heart",
    color: "text-rose-400",
    questions: [
      "Zero libido in my 20s - normal?",
      "Why does it hurt after sex?",
      "Natural testosterone/estrogen boosters",
      "Why is my cycle irregular?",
      "Signs of hormonal imbalance",
      "Why prone to UTIs constantly?",
      "Is Post-Coital Dysphoria real?",
      "Does stress actually shrink size?",
      "Why lose interest after finishing?",
      "How to talk about ED without shame?",
      "Is masturbation affecting my energy?",
      "Why do I feel guilty after masturbating?",
      "Low sex drive ruining relationship",
      "Pain during intercourse - what's wrong?",
      "Is porn addiction real or myth?",
      "Morning wood disappeared - should I worry?",
      "Why can't I finish during sex?",
      "Is death grip syndrome real?",
      "How to last longer naturally?",
      "Why do I get UTI after every time?",
      "Is blue balls actually dangerous?",
      "Why does my partner never want sex?",
      "Can you be allergic to condoms?",
      "Why do I bleed after sex?"
    ]
  },
  {
    id: "pregnancy",
    title: "Pregnancy & Fertility",
    icon: "Heart",
    color: "text-pink-400",
    questions: [
      "Early pregnancy symptoms before missed period",
      "Is cramping normal in first trimester?",
      "Why am I so emotional during pregnancy?",
      "Safe exercises during pregnancy",
      "How to deal with morning sickness?",
      "Signs of miscarriage vs normal cramping",
      "Can I have sex during pregnancy?",
      "Why can't I get pregnant after trying?",
      "Is it normal to regret being pregnant?",
      "Postpartum depression vs baby blues",
      "How long to wait after miscarriage?",
      "Fertility signs nobody talks about",
      "Why am I spotting during pregnancy?",
      "Is it safe to fly while pregnant?",
      "Why do I hate being pregnant?",
      "Can stress cause miscarriage?",
      "Why am I so tired in third trimester?",
      "Is my baby moving enough?",
      "Braxton Hicks vs real contractions",
      "Why does my vagina hurt during pregnancy?"
    ]
  },
  {
    id: "elderly",
    title: "Aging & Senior Health",
    icon: "Heart",
    color: "text-orange-400",
    questions: [
      "Why do my joints hurt more in morning?",
      "Is memory loss normal at my age?",
      "How to prevent osteoporosis naturally?",
      "Why am I losing muscle mass?",
      "Best supplements for aging adults",
      "Is it arthritis or just aging?",
      "How to maintain balance as I age?",
      "Why do I get dizzy standing up?",
      "Signs of early dementia vs forgetfulness",
      "How to stay active with chronic pain?",
      "Why do I need to pee so often?",
      "Is hearing loss reversible?",
      "Why are my hands shaking?",
      "How to prevent falls at home?",
      "Why do I feel cold all the time?"
    ]
  },
  {
    id: "heart",
    title: "Heart & Circulation",
    icon: "Heart",
    color: "text-red-500",
    questions: [
      "Why does my heart race randomly?",
      "Is chest pain anxiety or heart attack?",
      "Why do I feel my heartbeat in my head?",
      "High blood pressure in 20s - normal?",
      "Why do my hands go numb at night?",
      "Is heart palpitation dangerous?",
      "Why do I get lightheaded after standing?",
      "Cold hands and feet all the time",
      "Can stress cause heart problems?",
      "Why does my heart skip beats?",
      "Is my resting heart rate too high?",
      "Why do I feel pressure in chest?",
      "Can anxiety mimic heart attack?",
      "Why does my left arm hurt?",
      "Is irregular heartbeat serious?",
      "Why do I sweat at night?",
      "Can you die from broken heart?",
      "Why does my heart race after eating?"
    ]
  },
  {
    id: "liver",
    title: "Liver & Detox",
    icon: "AlertCircle",
    color: "text-yellow-400",
    questions: [
      "Signs of fatty liver disease",
      "Why is my pee dark yellow?",
      "Can liver repair itself after drinking?",
      "Is liver detox tea actually working?",
      "Why do I have pain under right rib?",
      "How long to detox liver naturally?",
      "Yellow eyes - is it jaundice?",
      "Best foods for liver health",
      "Can you reverse liver damage?",
      "Why do I feel nauseous after fatty food?",
      "Is my liver failing?",
      "Why does my stomach hurt after alcohol?",
      "Can you live without a liver?",
      "Why is my skin turning yellow?",
      "Is coffee good for liver?"
    ]
  },
  {
    id: "stress",
    title: "Stress & Burnout",
    icon: "Brain",
    color: "text-red-400",
    questions: [
      "Physical symptoms of chronic stress",
      "Why do I feel heat in my body?",
      "Stress headaches vs migraines",
      "Why am I so irritable lately?",
      "How to calm down during panic attack?",
      "Is my body in fight or flight mode?",
      "Why do I clench jaw while sleeping?",
      "Stress causing stomach problems",
      "How to recover from burnout fast?",
      "Why do I feel pressure in my head?",
      "Heat in mind - what does it mean?",
      "Body feels hot but no fever",
      "Why do I grind teeth at night?",
      "Can stress cause physical pain?",
      "Why am I always on edge?",
      "Is my cortisol too high?",
      "Why do I feel overwhelmed by everything?",
      "Can stress make you sick?"
    ]
  },
  {
    id: "badday",
    title: "Bad Days & Mood",
    icon: "Brain",
    color: "text-gray-400",
    questions: [
      "Why do I feel off for no reason?",
      "How to snap out of a bad mood?",
      "Feeling unmotivated to do anything",
      "Why am I so sensitive today?",
      "Everything annoying me suddenly",
      "How to reset after a terrible day?",
      "Why do I want to cry randomly?",
      "Feeling disconnected from reality",
      "Is it okay to have bad days?",
      "How to stop spiraling mentally?",
      "Why do I feel like giving up?",
      "Can't shake this heavy feeling",
      "Why does everything feel pointless?",
      "How to get out of a funk?",
      "Why am I so angry today?"
    ]
  },
  {
    id: "pain",
    title: "Pain & Aches",
    icon: "AlertCircle",
    color: "text-orange-500",
    questions: [
      "Why does my back hurt when I wake up?",
      "Is this headache a brain tumor?",
      "Why do my legs hurt at night?",
      "Sharp pain in side when breathing",
      "Why does my neck hurt on one side?",
      "Is this chest pain serious?",
      "Why do my feet hurt in morning?",
      "Constant lower back pain - what's wrong?",
      "Why does my shoulder hurt when I lift?",
      "Is this pain normal or emergency?",
      "Why do my hips hurt when sleeping?",
      "Stabbing pain in stomach randomly",
      "Why does my jaw hurt when chewing?",
      "Is this kidney pain or back pain?",
      "Why do my wrists hurt typing?"
    ]
  },
  {
    id: "skin",
    title: "Skin & Appearance",
    icon: "AlertCircle",
    color: "text-white",
    questions: [
      "Why is my hair thinning on one side?",
      "Does rosemary oil work for hair growth?",
      "Dark circles even with sleep?",
      "How to get rid of back acne scars?",
      "Why breaking out in my 30s?",
      "Does drinking water clear skin?",
      "Is preventative Botox a scam?",
      "Why do I look older in morning?",
      "How to tighten jawline naturally?",
      "Best vitamins for glowing skin?",
      "Why is my skin so dry suddenly?",
      "Is this mole cancerous?",
      "Why do I have bumps on arms?",
      "How to fade stretch marks?",
      "Why is my scalp so itchy?",
      "Can stress cause hair loss?",
      "Why do I have rash after shaving?",
      "Is this eczema or psoriasis?"
    ]
  },
  {
    id: "gut",
    title: "Gut & Nutrition",
    icon: "Apple",
    color: "text-amber-400",
    questions: [
      "Why do I look pregnant after eating?",
      "Is oat milk spiking my glucose?",
      "Foods that cause puffy face",
      "Why am I hungry after eating?",
      "How to fix bloating in 24 hours?",
      "Signs my gut microbiome is destroyed",
      "Why does coffee make me poop instantly?",
      "Is intermittent fasting ruining hormones?",
      "Why do I crave salt constantly?",
      "Does apple cider vinegar do anything?"
    ]
  },
  {
    id: "sleep",
    title: "Sleep & Energy",
    icon: "Moon",
    color: "text-indigo-400",
    questions: [
      "Why do I wake up at 3 AM every night?",
      "Can I catch up on sleep on weekends?",
      "Why groggy after 8 hours of sleep?",
      "Is taking Melatonin nightly dangerous?",
      "How to fall asleep in 2 minutes?",
      "Why exhausted at 2 PM daily?",
      "Does mouth taping actually help sleep?",
      "Why do I sleep better on couch?",
      "How to wake up without alarm naturally?",
      "Why do I dream so vividly lately?"
    ]
  },
  {
    id: "fitness",
    title: "Fitness & Body",
    icon: "Activity",
    color: "text-emerald-400",
    questions: [
      "Why does my lower back hurt sitting?",
      "How to fix 'Nerd Neck' posture?",
      "Can I build muscle without gym?",
      "Why do my knees click squatting?",
      "Is 10,000 steps necessary?",
      "How to lose love handles?",
      "Why do I get dizzy standing up?",
      "Is cardio killing my gains?",
      "Why are hamstrings always tight?",
      "Best exercise for people who hate running?"
    ]
  },
  {
    id: "baby",
    title: "Baby & Infant Care",
    icon: "Heart",
    color: "text-pink-400",
    questions: [
      "Why is my baby crying but not hungry?",
      "Is this red rash heat rash or eczema?",
      "Green poop in babies: Normal or infection?",
      "How to clear baby's blocked nose instantly?",
      "Signs of 'Silent Reflux' in infants",
      "White patches in baby's mouth: Thrush?",
      "Is my baby sleeping too much?",
      "When to worry about toddler fever?",
      "How to soothe teething pain at night?",
      "Is it safe to let them cry it out?"
    ]
  }
];